version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=dockerpass
      - POSTGRES_DB=pets
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acme.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg-data:
  pgadmin-data:
